site_name: FLEXSTRUCT

nav:
  - Home: index.md
  - Markets:
      - France: markets/01-france.md
      - Germany: markets/02-germany.md
      - Netherlands: markets/03-netherlands.md
      - Belgium: markets/04-belgium.md
      - Spain: markets/05-spain.md
      - UK: markets/06-united-kingdom.md
